version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/apps/scrybe"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/apps/shelf-snap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/apps/price-drop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/shared"
    schedule:
      interval: "weekly"
