package dev.scrybe.core.backup

/**
 * Names of the entries inside a backup's zip payload, and the rules for trusting one on the way in.
 *
 * A restore reads an archive **the user supplies**, which is a different trust level from anything
 * else in this app that opens a zip. `LocalModelManager.extractTarBz2` writes
 * `File(destDir, entry.name)` with no validation — tolerable for an archive downloaded from a known
 * URL, not tolerable here, where a crafted entry named `../../databases/scrybe-db` would be written
 * straight over the database. So entry names are validated rather than used.
 *
 * The rule is allow-listing, not blocking: an audio entry must look exactly like
 * `audio/<sessionId>.<ext>` with a session id this backup actually declares. Anything else is
 * refused. Trying to enumerate bad shapes — `..`, absolute paths, backslashes, encoded separators —
 * is the approach that keeps losing.
 */
internal object BackupEntryNames {
    const val MANIFEST = "manifest.json"
    const val DATABASE = "database.json"
    const val AUDIO_PREFIX = "audio/"

    /** Session ids are generated by `UUID.randomUUID().toString()`, so this is the whole alphabet. */
    private val SESSION_ID = Regex("[A-Za-z0-9-]{1,64}")
    private val EXTENSION = Regex("[A-Za-z0-9]{1,8}")

    fun audioEntry(
        sessionId: String,
        extension: String,
    ): String = "$AUDIO_PREFIX$sessionId.$extension"

    /**
     * The session id an audio entry belongs to, or null if the name is not one this build will
     * write — which is also the answer for anything hostile.
     *
     * Returning null rather than throwing because a stray entry should be skipped, not fail the
     * whole restore; a backup carrying one unexpected file is still worth recovering.
     */
    fun sessionIdOfAudioEntry(entryName: String): String? {
        if (!entryName.startsWith(AUDIO_PREFIX)) return null
        val remainder = entryName.removePrefix(AUDIO_PREFIX)
        // No nesting: exactly one path segment lives under audio/.
        if (remainder.contains('/') || remainder.contains('\\')) return null
        val dot = remainder.lastIndexOf('.')
        if (dot <= 0 || dot == remainder.length - 1) return null
        val sessionId = remainder.substring(0, dot)
        val extension = remainder.substring(dot + 1)
        if (!SESSION_ID.matches(sessionId)) return null
        if (!EXTENSION.matches(extension)) return null
        return sessionId
    }

    /** True for the two metadata entries a backup is required to contain. */
    fun isMetadataEntry(entryName: String): Boolean = entryName == MANIFEST || entryName == DATABASE
}
